# -*- coding: utf-8 -*-
"""BigQuery data fetching and query execution.

This module executes SQL queries against BigQuery and returns DataFrames.
Supports checkpoint-based caching to disk (parquet files) to avoid
re-querying during development/testing.

SQL queries are generated by QuerySpec.build_query() in queries.py.

Data is organized by platform -> source -> metric:
- Desktop has both 'glean' and 'legacy' sources
- Mobile has only 'glean' source

Functions:
- get_queries(): Build SQL queries for all platform/metric/source combinations
- get_aggregate_data(): Fetch all Desktop and Mobile metrics from BigQuery
"""

import datetime
from datetime import datetime as dt_datetime
import os
from typing import Dict, Optional, Set, Tuple

import pandas as pd
from google.cloud import bigquery
from .config import STATIC_CONFIG
from .queries import (
    QUERY_SPECS, Platform, Metric, TelemetrySource, DataSource, QuerySpec,
    get_availability_check_queries,
)

# Iran internet shutdown constants
IRAN_SHUTDOWN_DATE = "2026-02-27"
SYNTHETIC_PARQUET_PATH = "data/iran_synthetic/iran_synthetic.parquet"


def splice_iran_synthetic_data(
    datasets: Dict[str, Dict[str, Dict[str, pd.DataFrame]]],
    synthetic_parquet_path: str,
    shutdown_date: str,
) -> Dict[str, Dict[str, Dict[str, pd.DataFrame]]]:
    """Replace Iran data from shutdown_date onward with synthetic forecast data.

    Loads synthetic Iran forecast data from a parquet file and splices it into
    the real datasets, replacing any real Iran data from the shutdown date onward.
    The synthetic rows are converted to match BQ column types exactly (dbdate,
    Int64, nullable boolean) so that mozaic sees identical dtypes across all
    countries.

    The synthetic data covers dates through 2027-12-31, so it has headroom for
    any normal or backfill run. The splice extends synthetic IR data through the
    max date present in the real data for each metric, ensuring all countries
    share the same date set (required by mozaic's curate_mozaics).

    Args:
        datasets: Nested dict {platform: {source: {metric: DataFrame}}} from
            get_aggregate_data()
        synthetic_parquet_path: Path to the combined synthetic Iran parquet file
        shutdown_date: Date string (YYYY-MM-DD) from which to replace Iran data

    Returns:
        Modified datasets dict with Iran data spliced in

    Raises:
        FileNotFoundError: If synthetic parquet file doesn't exist
    """
    if not os.path.exists(synthetic_parquet_path):
        raise FileNotFoundError(
            f"Synthetic Iran data not found at {synthetic_parquet_path}. "
            f"Run scripts/generate_iran_synthetic.py first."
        )

    synthetic_df = pd.read_parquet(synthetic_parquet_path)
    shutdown_date_obj = dt_datetime.strptime(shutdown_date, "%Y-%m-%d").date()

    for platform, sources in datasets.items():
        for source, metrics in sources.items():
            for metric, real_df in metrics.items():
                # Filter synthetic data to this platform/source/metric
                mask = (
                    (synthetic_df["platform"] == platform)
                    & (synthetic_df["telemetry_source"] == source)
                    & (synthetic_df["metric"] == metric)
                )
                synthetic_slice = synthetic_df[mask].copy()

                if synthetic_slice.empty:
                    continue

                # Determine the max date in the real data. Synthetic IR must
                # cover through this date so all countries share the same
                # date set (mozaic requires historical_dates to match across
                # tiles).
                real_max_date = real_df["x"].max()

                # Convert synthetic x from Timestamp to datetime.date to
                # match BigQuery's dbdate dtype.
                synthetic_slice["x"] = (
                    pd.to_datetime(synthetic_slice["x"]).dt.date
                )

                # Filter synthetic to shutdown through max date in real data
                synthetic_slice = synthetic_slice[
                    (synthetic_slice["x"] >= shutdown_date_obj)
                    & (synthetic_slice["x"] <= real_max_date)
                ]

                if synthetic_slice.empty:
                    continue

                # Drop identifier columns
                synthetic_slice = synthetic_slice.drop(
                    columns=["platform", "telemetry_source", "metric"]
                )

                # Keep only columns that exist in the real DataFrame
                # (drops cross-platform segment columns, e.g., mobile cols
                # on desktop data)
                synthetic_slice = synthetic_slice[
                    [c for c in synthetic_slice.columns if c in real_df.columns]
                ]

                # Convert synthetic column types to match BQ output:
                #   y: float64 -> Int64 (nullable integer)
                #   segment bools: numpy bool -> nullable BooleanDtype
                synthetic_slice["y"] = (
                    synthetic_slice["y"].round().astype("Int64")
                )
                bool_cols = [
                    c for c in synthetic_slice.columns
                    if synthetic_slice[c].dtype == bool
                ]
                for col in bool_cols:
                    synthetic_slice[col] = synthetic_slice[col].astype("boolean")

                # Remove real Iran data from shutdown onward
                real_filtered = real_df[
                    ~(
                        (real_df["country"] == "IR")
                        & (real_df["x"] >= shutdown_date_obj)
                    )
                ]

                # Combine and sort
                combined = pd.concat(
                    [real_filtered, synthetic_slice], ignore_index=True
                )
                combined = combined.sort_values(["x", "country"]).reset_index(
                    drop=True
                )

                datasets[platform][source][metric] = combined

    return datasets


def check_training_data_availability(project: str, training_end_date: str) -> None:
    """Verify that all BigQuery tables have data through training_end_date.

    Runs a fast MAX(date_field) query against each unique table/date combination
    before the full pipeline starts. Raises immediately if any table is behind,
    saving ~90 minutes compared to discovering the issue at validation time.

    This commonly fails when running at 5 PM PST (= 1 AM UTC next day), because
    the Kubernetes pod computes training_end_date in UTC, referencing a date whose
    BigQuery data hasn't landed yet.

    Args:
        project: BigQuery project ID
        training_end_date: Required end date for training data (YYYY-MM-DD)

    Raises:
        ValueError: If any table's most recent data is before training_end_date,
                    with the unavailable table, available date, and a suggested
                    --forecast_start_date to use instead.
    """
    required_date = datetime.date.fromisoformat(training_end_date)
    checks = get_availability_check_queries()
    client = bigquery.Client(project)

    print(f"Pre-flight check: verifying training data is available through {training_end_date}...")

    for check in checks:
        result = client.query(check.sql).to_dataframe()
        max_date_raw = result['max_date'].iloc[0]

        if pd.isna(max_date_raw):
            raise ValueError(
                f"Pre-flight check failed: no data found in {check.table}.\n"
                f"  Date field: {check.date_field}\n"
                f"  Filter: {check.where_clause}\n"
            )

        max_date = pd.to_datetime(max_date_raw).date()

        if max_date < required_date:
            suggested_start = (max_date + datetime.timedelta(days=1)).isoformat()
            raise ValueError(
                f"Pre-flight check failed: training data not yet available.\n"
                f"  Table: {check.table}\n"
                f"  Required through: {training_end_date}\n"
                f"  Available through: {max_date}\n"
                f"\n"
                f"This commonly happens when the UTC date on the Kubernetes pod is ahead\n"
                f"of your local date (e.g., running at 5 PM PST which is 1 AM UTC next day).\n"
                f"\n"
                f"Suggested fix: --forecast_start_date {suggested_start}"
            )

    print(f"Pre-flight check passed: all tables have data through {training_end_date}.")


def get_queries(
    countries: str,
    data_source_filter: Optional[Set[DataSource]] = None,
    metric_filter: Optional[Set[Metric]] = None,
) -> Dict[str, Dict[str, Dict[str, Tuple[str, QuerySpec]]]]:
    """Build SQL queries for all platform/metric/source combinations.

    Args:
        countries: SQL-formatted country string (e.g., "'US', 'CA', 'GB'")
        data_source_filter: If set, only include specs matching these data sources
        metric_filter: If set, only include specs matching these metrics

    Returns:
        Nested dict structure: {platform: {source: {metric: (sql, spec)}}}
        Example:
        {
            'desktop': {
                'glean': {'DAU': (sql_string, QuerySpec), ...},
                'legacy': {'DAU': (sql_string, QuerySpec), ...}
            },
            'mobile': {
                'glean': {'DAU': (sql_string, QuerySpec), ...}
            }
        }
    """
    queries = {
        "desktop": {"glean": {}, "legacy": {}},
        "mobile": {"glean": {}}
    }

    for spec in QUERY_SPECS.values():
        if data_source_filter is not None and spec.data_source not in data_source_filter:
            continue
        if metric_filter is not None and spec.metric not in metric_filter:
            continue

        platform = spec.platform.value
        source = spec.telemetry_source.value
        metric = spec.metric.value
        sql = spec.build_query(countries)

        queries[platform][source][metric] = (sql, spec)

    return queries

# Get data
def get_aggregate_data(
    queries: Dict[str, Dict[str, Dict[str, Tuple[str, QuerySpec]]]],
    project: str,
    checkpoints: Optional[bool] = False,
    output_dir: Optional[str] = None,
) -> Dict[str, Dict[str, Dict[str, pd.DataFrame]]]:
    """Fetch all metrics from BigQuery with checkpoint support.

    Args:
        queries: Nested dict from get_queries() with structure {platform: {source: {metric: (sql, spec)}}}
        project: BigQuery project ID
        checkpoints: If True, save/load from parquet files
        output_dir: Directory for checkpoint files (defaults to current directory)

    Returns:
        Nested dict structure: {platform: {source: {metric: DataFrame}}}
    """
    resolved_output_dir = output_dir if output_dir is not None else "."

    datasets = {
        "desktop": {"glean": {}, "legacy": {}},
        "mobile": {"glean": {}}
    }

    # Use template from STATIC_CONFIG for checkpoint filenames
    filename_template = STATIC_CONFIG['raw_checkpoint_filename_template']

    # Calculate total queries for progress tracking
    total_queries = sum(len(metrics) for sources in queries.values() for metrics in sources.values())
    query_num = 0

    # Fetch query results and store the raw data
    # Iterate over platform -> source -> metric
    for platform, sources in queries.items():
        for source, metrics in sources.items():
            for metric, (query, spec) in metrics.items():
                query_num += 1
                checkpoint_filename = os.path.join(
                    resolved_output_dir,
                    filename_template.format(source=source, platform=platform, metric=metric)
                )
                df = None
                if checkpoints and os.path.exists(checkpoint_filename):
                    print(f'[{query_num}/{total_queries}] {spec.data_source.display_name} {metric} exists, loading')
                    df = pd.read_parquet(checkpoint_filename)
                else:
                    print(f"[{query_num}/{total_queries}] Querying {spec.data_source.display_name} {metric}")
                    print(query)
                    df = bigquery.Client(project).query(query).to_dataframe()

                    # Check for empty results
                    if df.empty:
                        raise ValueError(
                            f"BigQuery returned 0 rows for {spec.data_source.display_name} {metric}. "
                            f"Check if date range or country filter is too restrictive."
                        )

                    if checkpoints:
                        df.to_parquet(checkpoint_filename)
                datasets[platform][source][metric] = df

    return datasets
