# syntax=docker/dockerfile:1

# Builder stage for mozaic (no dependencies)

FROM --platform=linux/amd64 python:3.10.11-bullseye AS builder
#RUN python -m pip install -e 'git+https://github.com/mozilla/mozaic-forecasting#egg=mozaic'
RUN mkdir -p /wheel
#RUN pip wheel --no-deps -e 'git+https://github.com/brendanwells-moz/mozaic-forecasting@getters_branch#egg=mozaic' \
	#--wheel-dir /wheel

RUN git clone https://github.com/brendanwells-moz/mozaic-forecasting /src && \
    cd /src && git checkout getters_branch && \
    git rev-parse HEAD > /wheel/mozaic_commit.txt && \
    pip wheel --no-deps /src --wheel-dir /wheel

# Runtime stage

# For outerbounds, you should specify the platform as shown, even though that is not recommended online,
# or else flows run into issues (especially when images are built on Macs and then run on Outerbounds's remote node pool machines).
ARG TARGETPLATFORM
ARG TARGETARCH
FROM --platform=linux/amd64 python:3.10.11-slim-bullseye
RUN echo "building for $TARGETPLATFORM ($TARGETARCH)"

# Keeps Python from buffering stdout and stderr to avoid situations where
# the application crashes without emitting any logs due to buffering.
ENV PYTHONUNBUFFERED=1

# Puts the dependencies from this requirement list into the Docker environment for installation
COPY requirements.outerbounds.txt requirements.outerbounds.txt

# Installs aforementioned dependencies
RUN python -m pip install --no-cache-dir -r requirements.outerbounds.txt

# Install Mozaic from /wheel with no dependencies (they're bloated)
COPY --from=builder /wheel /wheel
RUN mv /wheel/mozaic_commit.txt /mozaic_commit.txt
RUN pip install --no-cache-dir --no-deps /wheel/* && rm -rf /wheel

# Install actual dependencies
RUN pip install --no-cache-dir \
      numpy \
      pandas \
      scipy \
      prophet \
      plotly \
      holidays \
      python-dateutil \
      tzdata

# Cleanup
RUN pip uninstall -y matplotlib fonttools wandb botocore kubernetes

RUN rm -rf /root/.cache/pip

# Additional code files
COPY mozaic_daily.py /

# Run a quick import test
RUN python -c "import mozmlops; print('mozmlops import OK')"
RUN python -c "import numpy, pandas, scipy, prophet, plotly, holidays; print('mozaic stack import #OK')"
RUN python -c "import mozaic; print('mozaic imports OK')"

